#
# Makefile for the input core drivers.
#

#obj-$(CONFIG_TOUCHSCREEN_GT917D_ZQL1628) += goodix_ts.o


#goodix_ts-objs := gt9xx.o
#goodix_ts-objs += gt9xx_update.o
#goodix_ts-objs += goodix_tool.o
#goodix_ts-objs += gt9xx_openshort.o

obj-$(CONFIG_TOUCHSCREEN_GT917D_ZQL1657) += gt9xx.o
obj-$(CONFIG_TOUCHSCREEN_GT917D_ZQL1657) += gt9xx_openshort.o
obj-$(CONFIG_TOUCHSCREEN_GT917D_ZQL1657) += gt9xx_update.o
obj-$(CONFIG_TOUCHSCREEN_GT917D_ZQL1657) += goodix_tool.o
