obj-$(CONFIG_CDFINGER_FP)	+= cdfinger_fp/
#Huaqin modify for silead driver by zhaojunhai1 at 2018/03/02 start
obj-$(CONFIG_SLSPI_DRIVER) += slspi/
#Huaqin modify for silead driver by zhaojunhai1 at 2018/03/02 end
